export const DEMO_USER = '99999999-9999-9999-9999-999999999999';

export const TOURS = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    title: '수도권 철도 스탬프 투어',
    description: '서울/경기 주요 역사와 철도 명소를 돌며 스탬프를 모으는 도시형 투어',
    category: 'railway',
    regionCode: '서울',
    difficulty: 'mid',
    duration: 'day',
    budget: 'low',
    period: 'always',
    status: 'active',
    reviewScore: 4.6,
    participants: 1240,
    reward: '기념 승차권 + 한정 배지',
    estimatedHours: 6,
    estimatedCost: '₩18,000',
    organizer: '한국철도공사',
    targetAudience: '누구나',
    verificationMethods: ['qr', 'manual'],
    milestones: [
      { stampCount: 1, reward: '참여 인증 스티커' },
      { stampCount: 2, reward: '철도 마그넷' },
      { stampCount: 3, reward: '기념 승차권 + 한정 배지' },
    ],
    notices: [
      '스탬프 비치대는 역사 내 안내센터 또는 대합실에 위치합니다.',
      '역사 운영시간 외에는 스탬프 수집이 불가합니다.',
      '기념품은 한정 수량으로 소진 시 변경될 수 있습니다.',
    ],
    contactInfo: {
      phone: '1544-7788',
      email: 'stamp@korail.com',
      website: 'https://www.letskorail.com',
    },
    tags: ['철도', '서울', '당일치기', '교통편리'],
    thumbnailEmoji: '🚂',
    spots: [
      {
        id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        name: '서울역',
        address: '서울 중구 한강대로 405',
        openHours: '05:00-24:00',
        description: '대한민국 철도의 출발점, 근대 건축물과 현대 역사가 공존하는 공간',
        verificationTypes: ['qr', 'manual'],
      },
      {
        id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab',
        name: '용산역',
        address: '서울 용산구 한강대로23길 55',
        openHours: '05:30-23:30',
        description: '용산 국제업무지구와 연결된 교통 허브, KTX·ITX 정차역',
        verificationTypes: ['qr', 'manual'],
      },
      {
        id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac',
        name: '수원역',
        address: '경기 수원시 팔달구 덕영대로 924',
        openHours: '05:00-24:00',
        description: '수원화성 인근의 경기 남부 대표 역사, 수원 관광의 시작점',
        verificationTypes: ['qr', 'manual'],
      },
    ],
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    title: '부산 바다 관광 스탬프',
    description: '해변·등대·전망대 중심의 부산 대표 관광지 스탬프 투어',
    category: 'sightseeing',
    regionCode: '부산',
    difficulty: 'beginner',
    duration: 'weekend',
    budget: 'mid',
    period: 'active',
    status: 'active',
    reviewScore: 4.8,
    participants: 980,
    reward: '완주 인증서 + 로컬 카페 쿠폰',
    estimatedHours: 10,
    estimatedCost: '₩42,000',
    organizer: '부산관광공사',
    targetAudience: '누구나',
    verificationMethods: ['gps', 'photo', 'manual'],
    milestones: [
      { stampCount: 1, reward: '부산 관광 엽서 세트' },
      { stampCount: 2, reward: '로컬 카페 음료 쿠폰' },
      { stampCount: 3, reward: '완주 인증서 + 로컬 카페 쿠폰' },
    ],
    notices: [
      '야외 스팟은 기상 상황에 따라 운영시간이 변동될 수 있습니다.',
      '오륙도 스카이워크는 바람이 강한 날 임시 폐쇄될 수 있습니다.',
      'GPS 인증은 스팟 반경 200m 이내에서 가능합니다.',
    ],
    contactInfo: {
      phone: '051-780-0000',
      email: 'tour@bto.or.kr',
      website: 'https://www.visitbusan.net',
    },
    tags: ['바다', '부산', '주말여행', '포토스팟'],
    thumbnailEmoji: '🌊',
    spots: [
      {
        id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        name: '광안리 해변',
        address: '부산 수영구 광안해변로',
        openHours: '상시 개방',
        description: '광안대교 야경이 아름다운 부산 대표 해변, 다양한 축제의 무대',
        verificationTypes: ['gps', 'photo'],
      },
      {
        id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbba',
        name: '오륙도 스카이워크',
        address: '부산 남구 오륙도로 137',
        openHours: '09:00-18:00',
        description: '절벽 위 유리 전망대에서 오륙도와 태평양을 조망하는 명소',
        verificationTypes: ['gps', 'photo', 'manual'],
      },
      {
        id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbc',
        name: '청사포 다릿돌전망대',
        address: '부산 해운대구 중동 산3-9',
        openHours: '09:00-18:00',
        description: '해운대 동쪽 끝 청사포 마을의 바다 위 전망대',
        verificationTypes: ['gps', 'photo'],
      },
    ],
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    title: '제주 감성 카페 스탬프 챌린지',
    description: '제주 동서남북 대표 카페를 방문하는 테마형 시즌 투어',
    category: 'theme',
    regionCode: '제주',
    difficulty: 'mid',
    duration: 'long',
    budget: 'high',
    period: 'upcoming',
    status: 'upcoming',
    reviewScore: 4.3,
    participants: 530,
    reward: '시즌 한정 굿즈',
    estimatedHours: 16,
    estimatedCost: '₩95,000',
    organizer: '제주관광공사',
    targetAudience: '누구나 (카페 메뉴 별도 구매 필요)',
    verificationMethods: ['photo', 'manual'],
    milestones: [
      { stampCount: 1, reward: '제주 감귤 키링' },
      { stampCount: 2, reward: '참여 카페 음료 할인 쿠폰' },
      { stampCount: 3, reward: '시즌 한정 굿즈 (에코백 + 스티커팩)' },
    ],
    notices: [
      '각 카페의 영업시간과 휴무일을 사전에 확인해주세요.',
      '음료 1잔 이상 주문 후 스탬프 인증이 가능합니다.',
      '시즌 투어 기간은 2026년 4월 1일 ~ 6월 30일입니다.',
      '기념품은 선착순 500명에게 제공됩니다.',
    ],
    contactInfo: {
      phone: '064-740-6000',
      email: 'cafe-tour@ijto.or.kr',
      website: 'https://www.visitjeju.net',
    },
    tags: ['카페', '제주', '감성여행', '시즌한정'],
    thumbnailEmoji: '☕',
    spots: [
      {
        id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
        name: '애월 오션뷰 카페',
        address: '제주 제주시 애월읍',
        openHours: '10:00-20:00',
        description: '애월 해안도로를 따라 위치한 오션뷰 카페, 제주 서쪽 대표 명소',
        verificationTypes: ['photo', 'manual'],
      },
      {
        id: 'cccccccc-cccc-cccc-cccc-ccccccccccca',
        name: '성산 일출 카페',
        address: '제주 서귀포시 성산읍',
        openHours: '09:00-19:00',
        description: '성산일출봉을 바라보며 커피를 즐길 수 있는 동쪽 인기 카페',
        verificationTypes: ['photo', 'manual'],
      },
      {
        id: 'cccccccc-cccc-cccc-cccc-cccccccccccb',
        name: '서귀포 가든 카페',
        address: '제주 서귀포시 강정동',
        openHours: '11:00-21:00',
        description: '열대 정원 속에 자리한 남쪽 힐링 카페, 넓은 야외 좌석 보유',
        verificationTypes: ['photo', 'manual'],
      },
    ],
  },
];

export const CATEGORY_OPTIONS = [
  { value: '', label: '전체 테마' },
  { value: 'railway', label: '철도' },
  { value: 'sightseeing', label: '관광' },
  { value: 'festival', label: '축제' },
  { value: 'local', label: '지역' },
  { value: 'theme', label: '테마' },
];

export const REGION_OPTIONS = [
  { value: '', label: '전체 지역' },
  { value: '서울', label: '서울' },
  { value: '부산', label: '부산' },
  { value: '제주', label: '제주' },
];

export const PERIOD_OPTIONS = [
  { value: '', label: '전체 기간' },
  { value: 'active', label: '진행 중' },
  { value: 'always', label: '상시' },
  { value: 'upcoming', label: '예정' },
];

export const SORT_OPTIONS = [
  { value: 'popular', label: '인기순' },
  { value: 'latest', label: '최신순' },
  { value: 'review', label: '리뷰순' },
];

export const VERIFICATION_OPTIONS = [
  { value: 'qr', label: 'QR 코드 스캔' },
  { value: 'gps', label: 'GPS 체크인' },
  { value: 'photo', label: '사진 업로드' },
  { value: 'manual', label: '수동 입력' },
];
